
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ADD DRAW CHECK BYE NAME1 NAME2 QUANTITY SMALL LARGE WHITE GREEN PLASTIC ALUMINUM OPEN CLOSE WEBSITE EXECUTABLE TXTPATHoperation : OPEN TXTPATHoperation : OPEN WEBSITEoperation : OPEN EXECUTABLEoperation : CLOSE EXECUTABLEoperation : ADD QUANTITY productoperation : DRAW QUANTITY productoperation : CHECK productoperation : BYEproduct : product_details NAMENAME : NAME1\n            | NAME2product_details : size color materialsize : SMALL\n            | LARGEcolor : WHITE\n             | GREENmaterial : ALUMINUM\n                | PLASTIC'
    
_lr_action_items = {'QUANTITY':([5,7,],[17,18,]),'NAME1':([10,27,28,29,],[19,-17,-18,-12,]),'TXTPATH':([3,],[13,]),'CHECK':([0,],[2,]),'EXECUTABLE':([3,4,],[14,16,]),'WHITE':([8,11,12,],[-14,-13,22,]),'OPEN':([0,],[3,]),'ALUMINUM':([22,23,24,],[-15,-16,27,]),'WEBSITE':([3,],[15,]),'CLOSE':([0,],[4,]),'LARGE':([2,17,18,],[8,8,8,]),'BYE':([0,],[6,]),'PLASTIC':([22,23,24,],[-15,-16,28,]),'ADD':([0,],[5,]),'$end':([1,6,9,13,14,15,16,19,20,21,25,26,],[0,-8,-7,-1,-3,-2,-4,-10,-11,-9,-5,-6,]),'DRAW':([0,],[7,]),'GREEN':([8,11,12,],[-14,-13,23,]),'NAME2':([10,27,28,29,],[20,-17,-18,-12,]),'SMALL':([2,17,18,],[11,11,11,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'product':([2,17,18,],[9,25,26,]),'operation':([0,],[1,]),'NAME':([10,],[21,]),'color':([12,],[24,]),'product_details':([2,17,18,],[10,10,10,]),'material':([24,],[29,]),'size':([2,17,18,],[12,12,12,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> operation","S'",1,None,None,None),
  ('operation -> OPEN TXTPATH','operation',2,'p_operation_open_txt','Konsola.py',137),
  ('operation -> OPEN WEBSITE','operation',2,'p_operation_open_website','Konsola.py',142),
  ('operation -> OPEN EXECUTABLE','operation',2,'p_operation_open_exe','Konsola.py',147),
  ('operation -> CLOSE EXECUTABLE','operation',2,'p_operation_close_exe','Konsola.py',157),
  ('operation -> ADD QUANTITY product','operation',3,'p_operation_add','Konsola.py',162),
  ('operation -> DRAW QUANTITY product','operation',3,'p_operation_draw','Konsola.py',172),
  ('operation -> CHECK product','operation',2,'p_operation_check','Konsola.py',185),
  ('operation -> BYE','operation',1,'p_operation_exit','Konsola.py',193),
  ('product -> product_details NAME','product',2,'p_product','Konsola.py',198),
  ('NAME -> NAME1','NAME',1,'p_name','Konsola.py',203),
  ('NAME -> NAME2','NAME',1,'p_name','Konsola.py',204),
  ('product_details -> size color material','product_details',3,'p_product_details','Konsola.py',209),
  ('size -> SMALL','size',1,'p_size','Konsola.py',214),
  ('size -> LARGE','size',1,'p_size','Konsola.py',215),
  ('color -> WHITE','color',1,'p_color','Konsola.py',220),
  ('color -> GREEN','color',1,'p_color','Konsola.py',221),
  ('material -> ALUMINUM','material',1,'p_material','Konsola.py',226),
  ('material -> PLASTIC','material',1,'p_material','Konsola.py',227),
]
