
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ADD DRAW CHECK BYE NAME1 NAME2 QUANTITY SMALL LARGE WHITE GREEN PLASTIC ALUMINUMoperation : ADD QUANTITY productoperation : DRAW QUANTITY productoperation : CHECK productoperation : BYEproduct : product_details NAMENAME : NAME1\n            | NAME2product_details : size color materialsize : SMALL\n            | LARGEcolor : WHITE\n             | GREENmaterial : ALUMINUM\n                | PLASTIC'
    
_lr_action_items = {'QUANTITY':([1,4,],[6,7,]),'ADD':([0,],[1,]),'NAME1':([12,21,22,23,],[19,-13,-8,-14,]),'WHITE':([8,9,10,],[17,-10,-9,]),'ALUMINUM':([15,16,17,],[21,-12,-11,]),'GREEN':([8,9,10,],[16,-10,-9,]),'NAME2':([12,21,22,23,],[20,-13,-8,-14,]),'BYE':([0,],[3,]),'DRAW':([0,],[4,]),'$end':([2,3,11,13,14,18,19,20,],[0,-4,-3,-1,-2,-5,-6,-7,]),'LARGE':([5,6,7,],[9,9,9,]),'CHECK':([0,],[5,]),'SMALL':([5,6,7,],[10,10,10,]),'PLASTIC':([15,16,17,],[23,-12,-11,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'color':([8,],[15,]),'size':([5,6,7,],[8,8,8,]),'material':([15,],[22,]),'operation':([0,],[2,]),'NAME':([12,],[18,]),'product':([5,6,7,],[11,13,14,]),'product_details':([5,6,7,],[12,12,12,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> operation","S'",1,None,None,None),
  ('operation -> ADD QUANTITY product','operation',3,'p_operation_add','C01.py',116),
  ('operation -> DRAW QUANTITY product','operation',3,'p_operation_draw','C01.py',126),
  ('operation -> CHECK product','operation',2,'p_operation_check','C01.py',139),
  ('operation -> BYE','operation',1,'p_operation_exit','C01.py',147),
  ('product -> product_details NAME','product',2,'p_product','C01.py',152),
  ('NAME -> NAME1','NAME',1,'p_name','C01.py',157),
  ('NAME -> NAME2','NAME',1,'p_name','C01.py',158),
  ('product_details -> size color material','product_details',3,'p_product_details','C01.py',163),
  ('size -> SMALL','size',1,'p_size','C01.py',168),
  ('size -> LARGE','size',1,'p_size','C01.py',169),
  ('color -> WHITE','color',1,'p_color','C01.py',174),
  ('color -> GREEN','color',1,'p_color','C01.py',175),
  ('material -> ALUMINUM','material',1,'p_material','C01.py',180),
  ('material -> PLASTIC','material',1,'p_material','C01.py',181),
]
